### ISSUE TITLE
PyPI package needs updating

### ISSUE THREAD

**Issue by mattgrayson** [oarrabi/mockpy#6]
Attempting to install via pip or by downloading directly from PyPi and running setup.py results in the traceback below:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5j/z25v44rx68n4w0b7_9rp229h0000gn/T/pip-build-id0gonmu/mockpy/setup.py", line 7, in <module>
        with open('Readme.md') as readme_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'
```

**Comment by xportation** [comment]
Any plans to solve this issue??

**Comment by nsomar** [comment]
Hello @xportation and @mattgrayson 
I am sorry about not answering earlier. I'm kinda overloaded at the moment.

It would be awesome If you'd help with PR here :). 

Sorry for not being able to spend more time on mockpy 🙁
